
'use client';

import { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Command, Activity, ChevronRight, Zap, Target, BookOpen } from 'lucide-react';
import Link from 'next/link';

export default function ExplorePage() {
  const [course, setCourse] = useState<any>(null);

  useEffect(() => {
    const saved = localStorage.getItem('current_course');
    if (saved) setCourse(JSON.parse(saved));
  }, []);

  return (
    <div className="min-h-screen bg-background font-sans flex flex-col">
      <header className="border-b border-border h-16 flex items-center justify-between px-8 bg-background/50 backdrop-blur-xl sticky top-0 z-50">
        <div className="flex items-center gap-4">
          <Link href="/" className="text-xs font-bold uppercase tracking-widest text-muted hover:text-foreground">LearnOS Home</Link>
          <div className="w-px h-4 bg-border" />
          <h1 className="text-xs font-bold uppercase tracking-widest text-accent">Cognitive IDE (Advanced)</h1>
        </div>
      </header>

      <main className="flex-1 p-12 max-w-[1400px] mx-auto w-full grid grid-cols-1 md:grid-cols-12 gap-12">
        <aside className="md:col-span-3 space-y-12">
          <section className="space-y-6">
            <h2 className="text-[10px] uppercase tracking-[0.3em] font-bold text-muted">Knowledge Index</h2>
            <div className="space-y-2">
              {['Thematic Maps', 'Neural Links', 'Archived Sessions', 'Mastery Logs'].map(f => (
                <div key={f} className="flex items-center gap-2 p-2 text-xs text-muted hover:text-foreground cursor-pointer transition-colors">
                  <ChevronRight className="w-3 h-3" />
                  {f}
                </div>
              ))}
            </div>
          </section>

          <section className="p-6 bg-accent/5 border border-accent/20 rounded-2xl space-y-4">
            <div className="flex items-center gap-2 text-accent">
              <Activity className="w-4 h-4" />
              <h3 className="text-[10px] uppercase font-bold tracking-widest">System Load</h3>
            </div>
            <div className="space-y-3">
              <div className="h-1 bg-border rounded-full overflow-hidden">
                <div className="h-full bg-accent" style={{ width: '12%' }} />
              </div>
              <p className="text-[9px] text-muted-foreground uppercase tracking-widest">Cognitive overhead: Low</p>
            </div>
          </section>
        </aside>

        <section className="md:col-span-6 space-y-12">
          <div className="p-8 bg-card border border-border rounded-3xl space-y-8">
            <header className="space-y-4">
              <div className="text-[10px] font-mono text-accent uppercase tracking-[0.2em] font-bold">Active Context</div>
              <h2 className="text-3xl font-medium tracking-tight">
                {course ? course.title : 'No Active Context'}
              </h2>
            </header>
            
            <div className="space-y-6">
              <p className="text-prose leading-relaxed text-muted-foreground">
                In this advanced mode, you can inspect the underlying semantic connections and structural patterns generated by the engine.
              </p>
              <div className="p-6 border border-border rounded-2xl bg-background/50 space-y-4">
                <div className="text-[10px] uppercase font-bold text-muted tracking-widest">Knowledge Nodes</div>
                <div className="flex flex-wrap gap-2">
                  {course?.knowledgeGraph.nodes.map((n: any) => (
                    <span key={n.id} className="px-3 py-1 bg-border/20 rounded-md text-[10px] font-mono">{n.label}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        <aside className="md:col-span-3 space-y-12">
          <section className="space-y-6">
            <h2 className="text-[10px] uppercase tracking-[0.3em] font-bold text-muted">Recent Sessions</h2>
            <div className="space-y-4">
              {course && (
                <div className="p-4 border border-border rounded-xl space-y-1">
                  <div className="text-[9px] text-accent font-bold uppercase">{course.difficulty}</div>
                  <div className="text-xs font-medium">{course.topic}</div>
                  <div className="text-[9px] text-muted-foreground">Synthesized today</div>
                </div>
              )}
            </div>
          </section>
          
          <Link href={course ? `/learn/${course.id}` : '#'} className="block p-6 bg-accent rounded-2xl text-white text-center shadow-xl shadow-accent/20 hover:scale-[1.02] transition-transform">
             <span className="text-xs font-bold uppercase tracking-widest">Return to Learning</span>
          </Link>
        </aside>
      </main>
    </div>
  );
}
